# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$pkg_name = ENV['PKG_NAME'] || Dir['*.tgz'].first
$node_tgz = ENV['NODE_TGZ'] || Dir['*-linux-x64.tar.gz'].first

$install_node = <<-SCRIPT
  which node && exit
  export PATH=/usr/local/bin:$PATH
  sudo tar -C /usr/local --strip-components 1 -xzf node-linux-x64.tar.gz
  sudo chown -R vagrant /usr/local
  npm install -g sl-service-install.tgz
SCRIPT

$testUpstart = <<SCRIPT
  export PATH=/usr/local/bin:$PATH
  # npm install -g sl-service-install.tgz
  #CentOS doesn't include /usr/local/bin in sudo PATH
  sudo PATH=$PATH $(which sl-svc-install) \
    --user `id -un` --name http-echo --cwd `pwd` --upstart $1 -- node ./echo.js 8888
  sudo /sbin/initctl start http-echo
  sudo /sbin/initctl status http-echo
  sleep 1
SCRIPT

$testSystemd = <<SCRIPT
  export PATH=/usr/local/bin:$PATH
  # npm install -g sl-service-install.tgz
  #CentOS doesn't include /usr/local/bin in sudo PATH
  sudo PATH=$PATH $(which sl-svc-install) \
    --user `id -un` --name http-echo --cwd `pwd` --systemd -- node ./echo.js 8888
  sudo systemctl start http-echo
  sudo systemctl status http-echo
  sleep 1
SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Cached version of node binaries
  config.vm.provision "file", source: $node_tgz, destination: "node-linux-x64.tar.gz"

  # The module under test
  config.vm.provision "file", source: $pkg_name, destination: "sl-service-install.tgz"

  # Test app
  config.vm.provision "file", source: "echo.js", destination: "echo.js"

  # Install the latest node stable
  config.vm.provision "shell", inline: $install_node

  # Ubuntu 12.04 for testing Upstart 1.4
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"

    # Install Upstart 1.4 job
    ubuntu.vm.provision "shell", inline: $testUpstart, privileged: false, args: ["1.4"]

    # Expose ports for test service
    ubuntu.vm.network "forwarded_port", guest: 8888, host: 10001, auto_correct: true
  end

  # Centos 6 for testing Upstart 0.6
  config.vm.define "centos6" do |centos|
    centos.vm.box = "chef/centos-6.6"

    # Install Upstart 0.6 job
    centos.vm.provision "shell", inline: $testUpstart, privileged: false, args: ["0.6"]

    # Expose ports for test services
    centos.vm.network "forwarded_port", guest: 8888, host: 10002, auto_correct: true
  end


  # Centos 7 for testing systemd
  config.vm.define "centos7" do |centos|
    centos.vm.box = "chef/centos-7.0"

    # Install systemd service
    centos.vm.provision "shell", inline: $testSystemd, privileged: false

    # Expose ports for test services
    centos.vm.network "forwarded_port", guest: 8888, host: 10003, auto_correct: true
  end
end
