# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$pkg_name = ENV['PKG_NAME'] || 'strong-service-install-0.0.0.tgz'
$node_tgz = ENV['NODE_TGZ'] || 'node-v0.10.29-linux-x64.tar.gz'

$bootstrap = <<SCRIPT
  test -f bootstrapped.txt && exit
  # apt-get update -y -qq
  apt-get install -y -qq build-essential git curl vim
  mkdir -p ~/.ssh; ssh-keyscan github.com >> ~/.ssh/known_hosts
  touch bootstrapped.txt
SCRIPT

$setup = <<SCRIPT
  rm -rf /usr/local/lib/node_modules
  tar -C /usr/local --strip-components 1 -xzf node-linux-x64.tar.gz
  chown -R vagrant /usr/local
SCRIPT

$test = <<SCRIPT
  mkdir -p ~/.ssh; ssh-keyscan github.com >> ~/.ssh/known_hosts
  npm install -g node-gyp > /dev/null
  node-gyp install &> /dev/null
  npm install -g sl-service-install.tgz
  sudo sl-svc-install --user `id -un` --name http-echo --cwd `pwd` -- node ./echo.js 8888
  test -f /etc/init/http-echo.conf
  sudo start http-echo
  sudo status http-echo
  sleep 1
  sudo tail -20 /var/log/upstart/http-echo.log
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Ubuntu 12.04 is a reasonable starting point
  config.vm.box = "ubuntu/precise64"

  # used for installing npm packages from private repos
  config.ssh.forward_agent = true

  # Version of nodejs tests are run against
  config.vm.provision "file", source: $node_tgz, destination: "node-linux-x64.tar.gz"

  # Ideally this part would be cached
  config.vm.provision "shell", inline: $bootstrap, privileged: true

  # Clear the environment and reset the state of Node
  config.vm.provision "shell", inline: $setup, privileged: true

  # The module under test
  config.vm.provision "file", source: $pkg_name, destination: "sl-service-install.tgz"
  config.vm.provision "file", source: "echo.js", destination: "echo.js"

  # Install modules for tests
  config.vm.provision "shell", inline: $test, privileged: false

  # expose sample app's port
  config.vm.network "forwarded_port", guest: 8888, host: 8888

end
